### PR TITLE
Add domain

### PR DESCRIPTION
**Pull request by PeyaPeyaPeyang**
*.google added
https://domains.google/

### CODE REVIEW

**Comment by Potato1682** [comment]
Can you add/delete other domains? I don't listing with English wikipedia.

**Review by Potato1682 — CHANGES_REQUESTED** [review]
Can you add/delete other domains? (Please check a Pull Request comment)

**Comment by PeyaPeyaPeyang** [comment]
Sorry, I don't know of a domain you can add other than .google,,

**Comment by PeyaPeyaPeyang** [comment]
no

**Comment by PeyaPeyaPeyang** [comment]
Please, look at [this](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) page.

**Comment by Potato1682** [comment]
Wow. That’s awesome. Is that an API?

**Comment by PeyaPeyaPeyang** [comment]
I think it's probably an API. And even if it's different, it's not overly access, so it's not likely to be a problem.

**Comment by Potato1682** [comment]
Can Program get domains? If possible, I want to implement auto domain update feature.

**Comment by PeyaPeyaPeyang** [comment]
I think you can save it as a temporary file and check the last modified date of the first line.

**Comment by Potato1682** [comment]
Yeah, that's good. But before I implement it in C#, I want to convert C# code to Javascript because Node.js (npm) is publishing many cli tool packages. C# (nuget) packages is not.

**Comment by Potato1682** [comment]
It's almost there, so I push converted code by the weekend.

**Comment by PeyaPeyaPeyang** [comment]
When you push, delete this pull request and the branch.

**Comment by Potato1682** [comment]
You already helped with IANA TLD List, so I want to close this pull request. Are you okay?

**Comment by PeyaPeyaPeyang** [comment]
yes

**Comment by Potato1682** [comment]
OK, Thank you very much. Close it.

**Pull request closed without merging**
